### PR TITLE
Few minor fixes; Organize files

### PR DESCRIPTION
**Pull request by smititelu**

### CODE REVIEW

**Comment by smititelu** [comment]
Hi @rsa9000,

I plan on playing and eventually coding further for this tool. I wonder if I can get write access to the repo.

Alternatively, I can do pull-requests.

Thanks,
Stefan

**Comment by rsa9000** [comment]
Hi @smititelu,

thank you for your contribution! I apply first two patches with fixes. The third commit, that rearrange files, needs more comments why this rearrange is required.

And if you intent to group source files in the src directory, then move build instructions there too, please. I.e. create a dedicated Makefile in the src directory, move build instructions from the top-level Makefile there, and then call binaries build Makefile from the top-level Makefile. So, all stuff related to then binary build (sources and build instructions) will be really isolated in the sub-directory.

As for repository write access. I have no strict plans for project evolving, except that I would like that it stay a FS recovery tool. And I have no objections to give a write access to a man who wish to continue the project.

Let begin from a few pull requests to see do we agree on a project evolving direction, code style and other minor stuff. And if everything will be alright, I will provide a direct access for you. Is it Ok for you?

**Comment by rsa9000** [comment]
Oh, and I forgot to note that the scripts are not a random miscellaneous stuff. They are essential part of the software and they are actively used to analyze the DB (see the workflow section of the readme). So, scripts intentionally placed together with the main binary to facilitate software usage immediately after binaries compilation without software installation to an OS.

In fact, I usually use sources root directory as a working directory for FS image recovery. E.g. my typical recovery workflow was:
* clone the repository;
* compile the binaries;
* put a disk image to the cloned repository directory;
* recover FS;
* write a recovered FS to a healthy disk;
* remove directory with cloned repository altogether with compiled binaries, the disk image and other stuff.

I know this is looks ugly from a recovery expert (user) point of view, but this was Ok for me as a developer who make utils for own usage.

So, think twice about pros and cons of moving scripts to a directory that is separated from the main binary.

**Comment by smititelu** [comment]
Hi @rsa9000,

Thanks alot for the feedback. I've amended last commit accordingly:
- created the top-level Makefile structure
- renamed `scripts` folder to `bin`
- when compilation is finished, the resulting binaries are also placed in the `bin` folder

Thus, I think the usual work flow you described above is left unmodified, just the disk image should be placed and recovered in `bin` folder now. What do you think?

Thanks,
Stefan

**Comment by rsa9000** [comment]
Hi @smititelu!

> Thus, I think the usual work flow you described above is left unmodified, just the disk image should be placed and recovered in `bin` folder now. What do you think?

Like a charm! Excellent solution with the `bin` sub-directory: source files grouped as you proposed and the old crazy workflow is still alive.

But the change still has no description of reasons. I am still a bit puzzled why would you like to group source files for such tiny project. And the commit message have no clues for the puzzle.

Please, make a final touch: add a reasons description to the commit message and I will merge the PR ASAP.

**Comment by smititelu** [comment]
hi @rsa9000,

Force pushed the commit with the updated description. 

IMHO this project looks to me more like a medium project with 78 source code files and 19939 lines of code :+1: 

Thanks,
Stefan

**Comment by rsa9000** [comment]
Applied. Thank you!

**Pull request merged**
