### PR TITLE
0.0.2: separate code and docs

### PR DESCRIPTION
**Pull request by zvezdochiot**
separate code and docs

### CODE REVIEW

**Comment by rsa9000** [comment]
Hello @zvezdochiot,

could you explain please, why do we need this change? And also describe why do you sort files by directories in such way (e.g. why do you place nhr-foo.sh files to the scripts directory)?

I am not against such rearrange, but this change require some explanation.

**Comment by zvezdochiot** [comment]
Hello @rsa9000 

The explanation is simple:

A person comes to the project page. And what does he see?

Option 1(your): Porridge from files with code, scripts and documentation;

Option 2(my): Documentation + separate code + separate scripts.

Enough visual comparison of your and my options.

**Comment by rsa9000** [comment]
> The explanation is simple:
> 
> A person comes to the project page. And what does he see?
> 
> Option 1(your): Porridge from files with code, scripts and documentation;
> 
> Option 2(my): Documentation + separate code + separate scripts.
> 
> Enough visual comparison of your and my options.

Ok, @zvezdochiot, what's wrong with this particular mix of scripts and source code? These scripts are not some kind of build helpers but an integral part of software. And BTW the documentation is already separated in the dedicated subdirectory.

**Comment by zvezdochiot** [comment]
Hello @rsa9000

>what's wrong with this particular mix of scripts and source code?

This is very inconvenient for code review and development.

>These scripts are not some kind of build helpers.

Therefore, they are moved to a separate directory. For the convenience of further development.

>the documentation is already separated in the dedicated subdirectory.

Not all

**Comment by rsa9000** [comment]
>> what's wrong with this particular mix of scripts and source code?
>
> This is very inconvenient for code review and development.
> 
>> These scripts are not some kind of build helpers.
>
> Therefore, they are moved to a separate directory. For the convenience of further development.
> 

I did not see a real use case, as well as any further development. So I would like to reject this PR, sorry. But I will keep in mind that not all users are happy with the current project files layout.

Fill free to create another one PR with more detailed description (possibly with use case examples).

**Comment by zvezdochiot** [comment]
See #2

**Pull request closed without merging**
